#!/bin/bash

export PROXY_IP=106.186.126.165
export IP=127.0.0.1
export NODE_ENV=production
export PORT=3000
export REGISTER_INVITATION=customInvitation
git pull
grunt build --force

cd dist;
ln -s ../node_modules .
forever start server/app.js -l node.log
